# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    fos_user.doctrine_registry:
        alias: doctrine

    app.mailer:
        class:        BackBundle\Services\AuthenticationListener
        arguments:    ['@mailer', '@doctrine', '%mailer_transport%']

    # authentication failure event listener
    acme.security.authentication_failure_event_listener:
        class: BackBundle\Services\AuthenticationListener
        arguments:    ['@mailer', '@doctrine', '%mailer_transport%']
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }

    # authentication success event listener
    acme.security.interactive_login_listener:
        class: BackBundle\Services\AuthenticationListener
        arguments:    ['@mailer', '@doctrine', '%mailer_transport%']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }