types_index:
    path:     /
    defaults: { _controller: "BackBundle:Types:index" }
    methods:  GET

types_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Types:show" }
    methods:  GET

types_new:
    path:     /new
    defaults: { _controller: "BackBundle:Types:new" }
    methods:  [GET, POST]

types_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Types:edit" }
    methods:  [GET, POST]

types_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Types:delete" }
    methods:  DELETE