<?php

namespace BackBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindByLocale($local="fr", $id){
		$q = $this->createQueryBuilder("c")
		  ->leftJoin("c.traduction", "t")->addSelect("t")
		  ->where("t.langue = :lg AND c.id = :id")
		  ->setParameters(array(
		  		"lg" => $local,
		  		"id" => $id));

		return $q->getQuery()->getResult();
	}

	public function findByLangue($local="fr"){
		$q = $this->createQueryBuilder("c")
		->leftJoin("c.traduction", "t")->addSelect("t")
			->where("c.langue = :lg");

		$q->setParameter("lg", $local); 
		$q = $q->getQuery();
		  
		return $q->getResult();
	}
}
