<?php

namespace BackBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCommande(){
		$q = $this->createQueryBuilder("c")
		  ->leftJoin("c.user", "u")->addSelect("u")
		  ->leftJoin("c.panier", "p")->addSelect("p")
		  ->leftJoin("p.produit", "pro")->addSelect("pro");

		$q = $q->getQuery();
		  
		return $q->getResult();
	}

}
