<?php

namespace BackBundle\Repository;

/**
 * MonnaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonnaieRepository extends \Doctrine\ORM\EntityRepository
{
}
