<?php

namespace BackBundle\Repository;


/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindProduct($local="fr"){
		$q = $this->createQueryBuilder("p")
		  ->leftJoin("p.traduction", "t")->addSelect("t")
		  ->leftJoin("t.categorie", "c")->addSelect("c")
		  ->leftJoin("t.type", "ty")->addSelect("ty")
		  ->where("t.langue = :lg")
		   ;
		$q->setParameter("lg", $local);   
		$q = $q->getQuery();
		  
		return $q->getResult();
	}

		public function FindByCategorie($local="fr", $id){
		$q = $this->createQueryBuilder("p")
		  ->leftJoin("p.traduction", "t")->addSelect("t")
		  ->leftJoin("t.categorie", "c")->addSelect("c")
		  ->leftJoin("t.type", "ty")->addSelect("ty");

		$q->where("c.id = :id")->setParameter("id", $id)
		  ->andWhere("t.langue = :lg")->setParameter("lg", $local);

		return $q->getQuery()->getResult();
	}
}