<?php

namespace BackBundle\Repository;

/**
 * TraductionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraductionsRepository extends \Doctrine\ORM\EntityRepository
{
/*
	public function myFindAll(){
		$q = $this->createQueryBuilder("t")
		  ->leftJoin("t.categorie", "c")->addSelect("c")
		  ->leftJoin("t.type", "ty")->addSelect("ty")
		;
		$q = $q->getQuery();
		  
		return $q->getResult();
	}
*/
}
