<?php

namespace BackBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
		public function MyfindBy(){
		$q = $this->createQueryBuilder("u")
		  ->leftJoin("u.adresse", "a")->addSelect("a");

		$q = $q->getQuery();
		  
		return $q->getResult();
	}
}
