<?php

namespace FrontBundle\Repository;


/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindProduct($local="fr"){
		$q = $this->createQueryBuilder("p")
		  ->leftJoin("p.traduction", "t")->addSelect("t")
		  ->leftJoin("t.categorie", "c")->addSelect("c")
		  ->leftJoin("t.type", "ty")->addSelect("ty")
		  ->where("t.langue = :lg")
		   ;
		$q->setParameter("lg", $local);   
		$q = $q->getQuery();
		  
		return $q->getResult();
	}
}
